//
// AccidentStatsAccidentStatsOrderedSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AccidentStatsAccidentStatsOrderedSummary: Codable {

    public var year: Int?
    public var borough: String?
    public var accidents: Int?

    public init(year: Int?, borough: String?, accidents: Int?) {
        self.year = year
        self.borough = borough
        self.accidents = accidents
    }


}

