//
// AccidentStatsAccidentDetail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AccidentStatsAccidentDetail: Codable {

    public var _id: Int?
    public var lat: Double?
    public var lon: Double?
    public var location: String?
    public var date: Date?
    public var severity: String?
    public var borough: String?
    public var casualties: [AccidentStatsCasualty]?
    public var vehicles: [AccidentStatsVehicle]?

    public init(_id: Int?, lat: Double?, lon: Double?, location: String?, date: Date?, severity: String?, borough: String?, casualties: [AccidentStatsCasualty]?, vehicles: [AccidentStatsVehicle]?) {
        self._id = _id
        self.lat = lat
        self.lon = lon
        self.location = location
        self.date = date
        self.severity = severity
        self.borough = borough
        self.casualties = casualties
        self.vehicles = vehicles
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case lat
        case lon
        case location
        case date
        case severity
        case borough
        case casualties
        case vehicles
    }


}

