//
// Crowding.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Crowding: Codable {

    /** Busiest times at a station (static information) */
    public var passengerFlows: [PassengerFlow]?
    /** Train Loading on a scale 1-6, 1 being \&quot;Very quiet\&quot; and 6 being \&quot;Exceptionally busy\&quot; (static information) */
    public var trainLoadings: [TrainLoading]?

    public init(passengerFlows: [PassengerFlow]?, trainLoadings: [TrainLoading]?) {
        self.passengerFlows = passengerFlows
        self.trainLoadings = trainLoadings
    }


}

