//
// FaresTicketType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FaresTicketType: Codable {

    public var type: String?
    public var _description: String?

    public init(type: String?, _description: String?) {
        self.type = type
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _description = "description"
    }


}

