//
// FaresRecommendation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FaresRecommendation: Codable {

    public var _id: Int?
    public var rule: Int?
    public var rank: Int?
    public var fareType: String?
    public var product: String?
    public var ticketType: String?
    public var ticketTime: String?
    public var productType: String?
    public var discountCard: String?
    public var zones: String?
    public var cost: String?
    public var priceDescription: String?
    public var priceComparison: String?
    public var recommendedTopUp: String?
    public var notes: [Message]?
    public var keyFeatures: [Message]?
    public var gettingYourTicket: [Message]?
    public var singleFare: Double?

    public init(_id: Int?, rule: Int?, rank: Int?, fareType: String?, product: String?, ticketType: String?, ticketTime: String?, productType: String?, discountCard: String?, zones: String?, cost: String?, priceDescription: String?, priceComparison: String?, recommendedTopUp: String?, notes: [Message]?, keyFeatures: [Message]?, gettingYourTicket: [Message]?, singleFare: Double?) {
        self._id = _id
        self.rule = rule
        self.rank = rank
        self.fareType = fareType
        self.product = product
        self.ticketType = ticketType
        self.ticketTime = ticketTime
        self.productType = productType
        self.discountCard = discountCard
        self.zones = zones
        self.cost = cost
        self.priceDescription = priceDescription
        self.priceComparison = priceComparison
        self.recommendedTopUp = recommendedTopUp
        self.notes = notes
        self.keyFeatures = keyFeatures
        self.gettingYourTicket = gettingYourTicket
        self.singleFare = singleFare
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case rule
        case rank
        case fareType
        case product
        case ticketType
        case ticketTime
        case productType
        case discountCard
        case zones
        case cost
        case priceDescription
        case priceComparison
        case recommendedTopUp
        case notes
        case keyFeatures
        case gettingYourTicket
        case singleFare
    }


}

