//
// FaresRecommendationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FaresRecommendationResponse: Codable {

    public var recommendations: [FaresRecommendation]?

    public init(recommendations: [FaresRecommendation]?) {
        self.recommendations = recommendations
    }


}

