//
// FaresFare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FaresFare: Codable {

    public var _id: Int?
    public var passengerType: String?
    public var validFrom: Date?
    public var validUntil: Date?
    public var ticketTime: String?
    public var ticketType: String?
    public var cost: String?
    public var cap: Double?
    public var _description: String?
    public var zone: String?
    public var mode: String?

    public init(_id: Int?, passengerType: String?, validFrom: Date?, validUntil: Date?, ticketTime: String?, ticketType: String?, cost: String?, cap: Double?, _description: String?, zone: String?, mode: String?) {
        self._id = _id
        self.passengerType = passengerType
        self.validFrom = validFrom
        self.validUntil = validUntil
        self.ticketTime = ticketTime
        self.ticketType = ticketType
        self.cost = cost
        self.cap = cap
        self._description = _description
        self.zone = zone
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case passengerType
        case validFrom
        case validUntil
        case ticketTime
        case ticketType
        case cost
        case cap
        case _description = "description"
        case zone
        case mode
    }


}

