//
// Instruction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Instruction: Codable {

    public var summary: String?
    public var detailed: String?
    public var steps: [InstructionStep]?

    public init(summary: String?, detailed: String?, steps: [InstructionStep]?) {
        self.summary = summary
        self.detailed = detailed
        self.steps = steps
    }


}

