//
// JourneyPlannerFareTapDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerFareTapDetails: Codable {

    public var modeType: String?
    public var validationType: String?
    public var hostDeviceType: String?
    public var busRouteId: String?
    public var nationalLocationCode: Int?
    public var tapTimestamp: Date?

    public init(modeType: String?, validationType: String?, hostDeviceType: String?, busRouteId: String?, nationalLocationCode: Int?, tapTimestamp: Date?) {
        self.modeType = modeType
        self.validationType = validationType
        self.hostDeviceType = hostDeviceType
        self.busRouteId = busRouteId
        self.nationalLocationCode = nationalLocationCode
        self.tapTimestamp = tapTimestamp
    }


}

