//
// JourneyPlannerSearchCriteria.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerSearchCriteria: Codable {

    public enum DateTimeType: String, Codable { 
        case arriving = "Arriving"
        case departing = "Departing"
    }
    public var dateTime: Date?
    public var dateTimeType: DateTimeType?
    public var timeAdjustments: JourneyPlannerTimeAdjustments?

    public init(dateTime: Date?, dateTimeType: DateTimeType?, timeAdjustments: JourneyPlannerTimeAdjustments?) {
        self.dateTime = dateTime
        self.dateTimeType = dateTimeType
        self.timeAdjustments = timeAdjustments
    }


}

