//
// JourneyPlannerObstacle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerObstacle: Codable {

    public var type: String?
    public var incline: String?
    public var stopId: Int?
    public var position: String?

    public init(type: String?, incline: String?, stopId: Int?, position: String?) {
        self.type = type
        self.incline = incline
        self.stopId = stopId
        self.position = position
    }


}

