//
// JourneyPlannerJourneyVector.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerJourneyVector: Codable {

    public var from: String?
    public var to: String?
    public var via: String?
    public var uri: String?

    public init(from: String?, to: String?, via: String?, uri: String?) {
        self.from = from
        self.to = to
        self.via = via
        self.uri = uri
    }


}

