//
// LineServiceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LineServiceType: Codable {

    public var lineName: String?
    public var lineSpecificServiceTypes: [LineSpecificServiceType]?

    public init(lineName: String?, lineSpecificServiceTypes: [LineSpecificServiceType]?) {
        self.lineName = lineName
        self.lineSpecificServiceTypes = lineSpecificServiceTypes
    }


}

