//
// Line.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Line: Codable {

    public var _id: String?
    public var name: String?
    public var modeName: String?
    public var disruptions: [Disruption]?
    public var created: Date?
    public var modified: Date?
    public var lineStatuses: [LineStatus]?
    public var routeSections: [MatchedRoute]?
    public var serviceTypes: [LineServiceTypeInfo]?
    public var crowding: Crowding?

    public init(_id: String?, name: String?, modeName: String?, disruptions: [Disruption]?, created: Date?, modified: Date?, lineStatuses: [LineStatus]?, routeSections: [MatchedRoute]?, serviceTypes: [LineServiceTypeInfo]?, crowding: Crowding?) {
        self._id = _id
        self.name = name
        self.modeName = modeName
        self.disruptions = disruptions
        self.created = created
        self.modified = modified
        self.lineStatuses = lineStatuses
        self.routeSections = routeSections
        self.serviceTypes = serviceTypes
        self.crowding = crowding
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case modeName
        case disruptions
        case created
        case modified
        case lineStatuses
        case routeSections
        case serviceTypes
        case crowding
    }


}

