//
// LineSpecificServiceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LineSpecificServiceType: Codable {

    public var serviceType: LineServiceTypeInfo?
    public var stopServesServiceType: Bool?

    public init(serviceType: LineServiceTypeInfo?, stopServesServiceType: Bool?) {
        self.serviceType = serviceType
        self.stopServesServiceType = stopServesServiceType
    }


}

