//
// PlacePolygon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlacePolygon: Codable {

    public var geoPoints: [GeoPoint]?
    public var commonName: String?

    public init(geoPoints: [GeoPoint]?, commonName: String?) {
        self.geoPoints = geoPoints
        self.commonName = commonName
    }


}

