//
// PostcodeInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostcodeInput: Codable {

    public var postcode: String?

    public init(postcode: String?) {
        self.postcode = postcode
    }


}

