//
// RoadDisruptionLine.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoadDisruptionLine: Codable {

    public var _id: Int?
    public var roadDisruptionId: String?
    public var isDiversion: Bool?
    public var multiLineString: SystemDataSpatialDbGeography?
    public var startDate: Date?
    public var endDate: Date?
    public var startTime: String?
    public var endTime: String?

    public init(_id: Int?, roadDisruptionId: String?, isDiversion: Bool?, multiLineString: SystemDataSpatialDbGeography?, startDate: Date?, endDate: Date?, startTime: String?, endTime: String?) {
        self._id = _id
        self.roadDisruptionId = roadDisruptionId
        self.isDiversion = isDiversion
        self.multiLineString = multiLineString
        self.startDate = startDate
        self.endDate = endDate
        self.startTime = startTime
        self.endTime = endTime
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case roadDisruptionId
        case isDiversion
        case multiLineString
        case startDate
        case endDate
        case startTime
        case endTime
    }


}

