//
// RouteSectionNaptanEntrySequence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RouteSectionNaptanEntrySequence: Codable {

    public var ordinal: Int?
    public var stopPoint: StopPoint?

    public init(ordinal: Int?, stopPoint: StopPoint?) {
        self.ordinal = ordinal
        self.stopPoint = stopPoint
    }


}

