//
// StopPointRouteSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StopPointRouteSection: Codable {

    public var naptanId: String?
    public var lineId: String?
    public var mode: String?
    public var validFrom: Date?
    public var validTo: Date?
    public var direction: String?
    public var routeSectionName: String?
    public var lineString: String?
    public var isActive: Bool?
    public var serviceType: String?
    public var vehicleDestinationText: String?
    public var destinationName: String?

    public init(naptanId: String?, lineId: String?, mode: String?, validFrom: Date?, validTo: Date?, direction: String?, routeSectionName: String?, lineString: String?, isActive: Bool?, serviceType: String?, vehicleDestinationText: String?, destinationName: String?) {
        self.naptanId = naptanId
        self.lineId = lineId
        self.mode = mode
        self.validFrom = validFrom
        self.validTo = validTo
        self.direction = direction
        self.routeSectionName = routeSectionName
        self.lineString = lineString
        self.isActive = isActive
        self.serviceType = serviceType
        self.vehicleDestinationText = vehicleDestinationText
        self.destinationName = destinationName
    }


}

