//
// TimetableResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TimetableResponse: Codable {

    public var lineId: String?
    public var lineName: String?
    public var direction: String?
    public var pdfUrl: String?
    public var stations: [MatchedStop]?
    public var stops: [MatchedStop]?
    public var timetable: Timetable?
    public var disambiguation: TimetablesDisambiguation?
    public var statusErrorMessage: String?

    public init(lineId: String?, lineName: String?, direction: String?, pdfUrl: String?, stations: [MatchedStop]?, stops: [MatchedStop]?, timetable: Timetable?, disambiguation: TimetablesDisambiguation?, statusErrorMessage: String?) {
        self.lineId = lineId
        self.lineName = lineName
        self.direction = direction
        self.pdfUrl = pdfUrl
        self.stations = stations
        self.stops = stops
        self.timetable = timetable
        self.disambiguation = disambiguation
        self.statusErrorMessage = statusErrorMessage
    }


}

