//
// TimetablesDisambiguation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TimetablesDisambiguation: Codable {

    public var disambiguationOptions: [TimetablesDisambiguationOption]?

    public init(disambiguationOptions: [TimetablesDisambiguationOption]?) {
        self.disambiguationOptions = disambiguationOptions
    }


}

