//
// TimetableRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TimetableRoute: Codable {

    public var stationIntervals: [StationInterval]?
    public var schedules: [Schedule]?

    public init(stationIntervals: [StationInterval]?, schedules: [Schedule]?) {
        self.stationIntervals = stationIntervals
        self.schedules = schedules
    }


}

