//
// VehicleMatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */

public struct VehicleMatch: Codable {

    public enum Compliance: String, Codable { 
        case notAvailable = "NotAvailable"
        case notCompliant = "NotCompliant"
        case compliant = "Compliant"
        case exempt = "Exempt"
    }
    public var vrm: String?
    public var type: String?
    public var make: String?
    public var model: String?
    public var colour: String?
    public var compliance: Compliance?

    public init(vrm: String?, type: String?, make: String?, model: String?, colour: String?, compliance: Compliance?) {
        self.vrm = vrm
        self.type = type
        self.make = make
        self.model = model
        self.colour = colour
        self.compliance = compliance
    }


}

