//
// Period.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Period: Codable {

    public enum ModelType: String, Codable { 
        case normal = "Normal"
        case frequencyHours = "FrequencyHours"
        case frequencyMinutes = "FrequencyMinutes"
        case unknown = "Unknown"
    }
    public var type: ModelType?
    public var fromTime: TwentyFourHourClockTime?
    public var toTime: TwentyFourHourClockTime?
    public var frequency: ServiceFrequency?

    public init(type: ModelType?, fromTime: TwentyFourHourClockTime?, toTime: TwentyFourHourClockTime?, frequency: ServiceFrequency?) {
        self.type = type
        self.fromTime = fromTime
        self.toTime = toTime
        self.frequency = frequency
    }


}

