//
// RouteSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RouteSection: Codable {

    /** The Id of the route */
    public var _id: String?
    /** The Id of the Line */
    public var lineId: String?
    /** The route code */
    public var routeCode: String?
    /** Name such as \&quot;72\&quot; */
    public var name: String?
    /** The co-ordinates of the route&#39;s path as a geoJSON lineString */
    public var lineString: String?
    /** Inbound or Outbound */
    public var direction: String?
    /** The name of the Origin StopPoint */
    public var originationName: String?
    /** The name of the Destination StopPoint */
    public var destinationName: String?
    /** The DateTime that the Service containing this Route is valid until. */
    public var validTo: Date?
    /** The DateTime that the Service containing this Route is valid from. */
    public var validFrom: Date?
    public var routeSectionNaptanEntrySequence: [RouteSectionNaptanEntrySequence]?

    public init(_id: String?, lineId: String?, routeCode: String?, name: String?, lineString: String?, direction: String?, originationName: String?, destinationName: String?, validTo: Date?, validFrom: Date?, routeSectionNaptanEntrySequence: [RouteSectionNaptanEntrySequence]?) {
        self._id = _id
        self.lineId = lineId
        self.routeCode = routeCode
        self.name = name
        self.lineString = lineString
        self.direction = direction
        self.originationName = originationName
        self.destinationName = destinationName
        self.validTo = validTo
        self.validFrom = validFrom
        self.routeSectionNaptanEntrySequence = routeSectionNaptanEntrySequence
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case lineId
        case routeCode
        case name
        case lineString
        case direction
        case originationName
        case destinationName
        case validTo
        case validFrom
        case routeSectionNaptanEntrySequence
    }


}

