//
// JourneyPlannerFare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerFare: Codable {

    public var lowZone: Int?
    public var highZone: Int?
    public var cost: Int?
    public var chargeProfileName: String?
    public var isHopperFare: Bool?
    public var chargeLevel: String?
    public var peak: Int?
    public var offPeak: Int?
    public var taps: [JourneyPlannerFareTap]?

    public init(lowZone: Int?, highZone: Int?, cost: Int?, chargeProfileName: String?, isHopperFare: Bool?, chargeLevel: String?, peak: Int?, offPeak: Int?, taps: [JourneyPlannerFareTap]?) {
        self.lowZone = lowZone
        self.highZone = highZone
        self.cost = cost
        self.chargeProfileName = chargeProfileName
        self.isHopperFare = isHopperFare
        self.chargeLevel = chargeLevel
        self.peak = peak
        self.offPeak = offPeak
        self.taps = taps
    }


}

