//
// PlaceCategory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlaceCategory: Codable {

    public var category: String?
    public var availableKeys: [String]?

    public init(category: String?, availableKeys: [String]?) {
        self.category = category
        self.availableKeys = availableKeys
    }


}

