//
// RouteSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RouteSearchResponse: Codable {

    public var input: String?
    public var searchMatches: [RouteSearchMatch]?

    public init(input: String?, searchMatches: [RouteSearchMatch]?) {
        self.input = input
        self.searchMatches = searchMatches
    }


}

