//
// PassengerFlow.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PassengerFlow: Codable {

    /** Time in 24hr format with 15 minute intervals e.g. 0500-0515, 0515-0530 etc. */
    public var timeSlice: String?
    /** Count of passenger flow towards a platform */
    public var value: Int?

    public init(timeSlice: String?, value: Int?) {
        self.timeSlice = timeSlice
        self.value = value
    }


}

