//
// ValidityPeriod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a period for which a planned works is valid. */

public struct ValidityPeriod: Codable {

    /** Gets or sets the start date. */
    public var fromDate: Date?
    /** Gets or sets the end date. */
    public var toDate: Date?
    /** If true is a realtime status rather than planned or info */
    public var isNow: Bool?

    public init(fromDate: Date?, toDate: Date?, isNow: Bool?) {
        self.fromDate = fromDate
        self.toDate = toDate
        self.isNow = isNow
    }


}

