//
// JourneyPlannerPath.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerPath: Codable {

    public var lineString: String?
    public var stopPoints: [Identifier]?
    public var elevation: [JourneyPlannerJpElevation]?

    public init(lineString: String?, stopPoints: [Identifier]?, elevation: [JourneyPlannerJpElevation]?) {
        self.lineString = lineString
        self.stopPoints = stopPoints
        self.elevation = elevation
    }


}

