//
// JourneyPlannerTimeAdjustments.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerTimeAdjustments: Codable {

    public var earliest: JourneyPlannerTimeAdjustment?
    public var earlier: JourneyPlannerTimeAdjustment?
    public var later: JourneyPlannerTimeAdjustment?
    public var latest: JourneyPlannerTimeAdjustment?

    public init(earliest: JourneyPlannerTimeAdjustment?, earlier: JourneyPlannerTimeAdjustment?, later: JourneyPlannerTimeAdjustment?, latest: JourneyPlannerTimeAdjustment?) {
        self.earliest = earliest
        self.earlier = earlier
        self.later = later
        self.latest = latest
    }


}

