//
// Prediction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** DTO to capture the prediction details */

public struct Prediction: Codable {

    /** The identitier for the prediction */
    public var _id: String?
    /** The type of the operation (1: is new or has been updated, 2: should be deleted from any client cache) */
    public var operationType: Int?
    /** The actual vehicle in transit (for train modes, the leading car of the rolling set) */
    public var vehicleId: String?
    /** Identifier for the prediction */
    public var naptanId: String?
    /** Station name */
    public var stationName: String?
    /** Unique identifier for the Line */
    public var lineId: String?
    /** Line Name */
    public var lineName: String?
    /** Platform name (for bus, this is the stop letter) */
    public var platformName: String?
    /** Direction (unified to inbound/outbound) */
    public var direction: String?
    /** Bearing (between 0 to 359) */
    public var bearing: String?
    /** Naptan Identifier for the prediction&#39;s destination */
    public var destinationNaptanId: String?
    /** Name of the destination */
    public var destinationName: String?
    /** Timestamp for when the prediction was inserted/modified (source column drives what objects are broadcast on each iteration) */
    public var timestamp: Date?
    /** Prediction of the Time to station in seconds */
    public var timeToStation: Int?
    /** The current location of the vehicle. */
    public var currentLocation: String?
    /** Routing information or other descriptive text about the path of the vehicle towards the destination */
    public var towards: String?
    /** The expected arrival time of the vehicle at the stop/station */
    public var expectedArrival: Date?
    /** The expiry time for the prediction */
    public var timeToLive: Date?
    /** The mode name of the station/line the prediction relates to */
    public var modeName: String?
    /** Keep the original timestamp from MongoDb fo debugging purposes */
    public var timing: PredictionTiming?

    public init(_id: String?, operationType: Int?, vehicleId: String?, naptanId: String?, stationName: String?, lineId: String?, lineName: String?, platformName: String?, direction: String?, bearing: String?, destinationNaptanId: String?, destinationName: String?, timestamp: Date?, timeToStation: Int?, currentLocation: String?, towards: String?, expectedArrival: Date?, timeToLive: Date?, modeName: String?, timing: PredictionTiming?) {
        self._id = _id
        self.operationType = operationType
        self.vehicleId = vehicleId
        self.naptanId = naptanId
        self.stationName = stationName
        self.lineId = lineId
        self.lineName = lineName
        self.platformName = platformName
        self.direction = direction
        self.bearing = bearing
        self.destinationNaptanId = destinationNaptanId
        self.destinationName = destinationName
        self.timestamp = timestamp
        self.timeToStation = timeToStation
        self.currentLocation = currentLocation
        self.towards = towards
        self.expectedArrival = expectedArrival
        self.timeToLive = timeToLive
        self.modeName = modeName
        self.timing = timing
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case operationType
        case vehicleId
        case naptanId
        case stationName
        case lineId
        case lineName
        case platformName
        case direction
        case bearing
        case destinationNaptanId
        case destinationName
        case timestamp
        case timeToStation
        case currentLocation
        case towards
        case expectedArrival
        case timeToLive
        case modeName
        case timing
    }


}

