//
// LineServiceTypeInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LineServiceTypeInfo: Codable {

    public var name: String?
    public var uri: String?

    public init(name: String?, uri: String?) {
        self.name = name
        self.uri = uri
    }


}

