//
// StopPointSequence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StopPointSequence: Codable {

    public enum ServiceType: String, Codable { 
        case regular = "Regular"
        case night = "Night"
    }
    public var lineId: String?
    public var lineName: String?
    public var direction: String?
    /** The id of this branch. */
    public var branchId: Int?
    /** The ids of the next branch(es) in the sequence. Note that the next and previous branch id can be              identical in the case of a looped route e.g. the Circle line. */
    public var nextBranchIds: [Int]?
    /** The ids of the previous branch(es) in the sequence. Note that the next and previous branch id can be              identical in the case of a looped route e.g. the Circle line. */
    public var prevBranchIds: [Int]?
    public var stopPoint: [MatchedStop]?
    public var serviceType: ServiceType?

    public init(lineId: String?, lineName: String?, direction: String?, branchId: Int?, nextBranchIds: [Int]?, prevBranchIds: [Int]?, stopPoint: [MatchedStop]?, serviceType: ServiceType?) {
        self.lineId = lineId
        self.lineName = lineName
        self.direction = direction
        self.branchId = branchId
        self.nextBranchIds = nextBranchIds
        self.prevBranchIds = prevBranchIds
        self.stopPoint = stopPoint
        self.serviceType = serviceType
    }


}

