//
// JourneyPlannerFareTap.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct JourneyPlannerFareTap: Codable {

    public var atcoCode: String?
    public var tapDetails: JourneyPlannerFareTapDetails?

    public init(atcoCode: String?, tapDetails: JourneyPlannerFareTapDetails?) {
        self.atcoCode = atcoCode
        self.tapDetails = tapDetails
    }


}

