//
// RouteSequence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RouteSequence: Codable {

    public var lineId: String?
    public var lineName: String?
    public var direction: String?
    public var isOutboundOnly: Bool?
    public var mode: String?
    public var lineStrings: [String]?
    public var stations: [MatchedStop]?
    public var stopPointSequences: [StopPointSequence]?
    public var orderedLineRoutes: [OrderedRoute]?

    public init(lineId: String?, lineName: String?, direction: String?, isOutboundOnly: Bool?, mode: String?, lineStrings: [String]?, stations: [MatchedStop]?, stopPointSequences: [StopPointSequence]?, orderedLineRoutes: [OrderedRoute]?) {
        self.lineId = lineId
        self.lineName = lineName
        self.direction = direction
        self.isOutboundOnly = isOutboundOnly
        self.mode = mode
        self.lineStrings = lineStrings
        self.stations = stations
        self.stopPointSequences = stopPointSequences
        self.orderedLineRoutes = orderedLineRoutes
    }


}

