//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Message: Codable {

    public var bulletOrder: Int?
    public var header: Bool?
    public var messageText: String?
    public var linkText: String?
    public var url: String?

    public init(bulletOrder: Int?, header: Bool?, messageText: String?, linkText: String?, url: String?) {
        self.bulletOrder = bulletOrder
        self.header = header
        self.messageText = messageText
        self.linkText = linkText
        self.url = url
    }


}

