//
// RouteSearchMatch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RouteSearchMatch: Codable {

    public var lineId: String?
    public var mode: String?
    public var lineName: String?
    public var lineRouteSection: [LineRouteSection]?
    public var matchedRouteSections: [MatchedRouteSections]?
    public var matchedStops: [MatchedStop]?
    public var _id: String?
    public var url: String?
    public var name: String?
    public var lat: Double?
    public var lon: Double?

    public init(lineId: String?, mode: String?, lineName: String?, lineRouteSection: [LineRouteSection]?, matchedRouteSections: [MatchedRouteSections]?, matchedStops: [MatchedStop]?, _id: String?, url: String?, name: String?, lat: Double?, lon: Double?) {
        self.lineId = lineId
        self.mode = mode
        self.lineName = lineName
        self.lineRouteSection = lineRouteSection
        self.matchedRouteSections = matchedRouteSections
        self.matchedStops = matchedStops
        self._id = _id
        self.url = url
        self.name = name
        self.lat = lat
        self.lon = lon
    }

    public enum CodingKeys: String, CodingKey { 
        case lineId
        case mode
        case lineName
        case lineRouteSection
        case matchedRouteSections
        case matchedStops
        case _id = "id"
        case url
        case name
        case lat
        case lon
    }


}

