//
// StationInterval.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StationInterval: Codable {

    public var _id: String?
    public var intervals: [Interval]?

    public init(_id: String?, intervals: [Interval]?) {
        self._id = _id
        self.intervals = intervals
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case intervals
    }


}

