//
// TflApiPresentationEntitiesFaresFaresSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesFaresFaresSection: Codable {

    public var header: String?
    public var index: Int?
    public var rows: [TflApiPresentationEntitiesFaresFareDetails]?
    public var messages: [TflApiPresentationEntitiesMessage]?

    public init(header: String?, index: Int?, rows: [TflApiPresentationEntitiesFaresFareDetails]?, messages: [TflApiPresentationEntitiesMessage]?) {
        self.header = header
        self.index = index
        self.rows = rows
        self.messages = messages
    }


}

