//
// TflApiPresentationEntitiesLineSpecificServiceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesLineSpecificServiceType: Codable {

    public var serviceType: TflApiPresentationEntitiesLineServiceTypeInfo?
    public var stopServesServiceType: Bool?

    public init(serviceType: TflApiPresentationEntitiesLineServiceTypeInfo?, stopServesServiceType: Bool?) {
        self.serviceType = serviceType
        self.stopServesServiceType = stopServesServiceType
    }


}

