//
// TflApiPresentationEntitiesBikePointOccupancy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Bike point occupancy */

public struct TflApiPresentationEntitiesBikePointOccupancy: Codable {

    /** Id of the bike point such as BikePoints_1 */
    public var _id: String?
    /** Name / Common name of the bike point */
    public var name: String?
    /** Total bike counts */
    public var bikesCount: Int?
    /** Empty docks */
    public var emptyDocks: Int?
    /** Total docks available */
    public var totalDocks: Int?

    public init(_id: String?, name: String?, bikesCount: Int?, emptyDocks: Int?, totalDocks: Int?) {
        self._id = _id
        self.name = name
        self.bikesCount = bikesCount
        self.emptyDocks = emptyDocks
        self.totalDocks = totalDocks
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case bikesCount
        case emptyDocks
        case totalDocks
    }


}

