//
// TflApiPresentationEntitiesPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a point located at a latitude and longitude using the WGS84 co-ordinate system. */

public struct TflApiPresentationEntitiesPoint: Codable {

    /** WGS84 latitude of the location. */
    public var lat: Double?
    /** WGS84 longitude of the location. */
    public var lon: Double?

    public init(lat: Double?, lon: Double?) {
        self.lat = lat
        self.lon = lon
    }


}

