//
// TflApiPresentationEntitiesPlacePolygon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesPlacePolygon: Codable {

    public var geoPoints: [TflApiCommonGeoPoint]?
    public var commonName: String?

    public init(geoPoints: [TflApiCommonGeoPoint]?, commonName: String?) {
        self.geoPoints = geoPoints
        self.commonName = commonName
    }


}

