//
// TflApiPresentationEntitiesServiceFrequency.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesServiceFrequency: Codable {

    public var lowestFrequency: Double?
    public var highestFrequency: Double?

    public init(lowestFrequency: Double?, highestFrequency: Double?) {
        self.lowestFrequency = lowestFrequency
        self.highestFrequency = highestFrequency
    }


}

