//
// TflApiPresentationEntitiesRouteSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesRouteSearchResponse: Codable {

    public var input: String?
    public var searchMatches: [TflApiPresentationEntitiesRouteSearchMatch]?

    public init(input: String?, searchMatches: [TflApiPresentationEntitiesRouteSearchMatch]?) {
        self.input = input
        self.searchMatches = searchMatches
    }


}

