//
// TflApiPresentationEntitiesAccidentStatsCasualty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesAccidentStatsCasualty: Codable {

    public var age: Int?
    public var _class: String?
    public var severity: String?
    public var mode: String?
    public var ageBand: String?

    public init(age: Int?, _class: String?, severity: String?, mode: String?, ageBand: String?) {
        self.age = age
        self._class = _class
        self.severity = severity
        self.mode = mode
        self.ageBand = ageBand
    }

    public enum CodingKeys: String, CodingKey { 
        case age
        case _class = "class"
        case severity
        case mode
        case ageBand
    }


}

