//
// TflApiPresentationEntitiesCarParkOccupancy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesCarParkOccupancy: Codable {

    public var _id: String?
    public var bays: [TflApiPresentationEntitiesBay]?
    public var name: String?
    public var carParkDetailsUrl: String?

    public init(_id: String?, bays: [TflApiPresentationEntitiesBay]?, name: String?, carParkDetailsUrl: String?) {
        self._id = _id
        self.bays = bays
        self.name = name
        self.carParkDetailsUrl = carParkDetailsUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case bays
        case name
        case carParkDetailsUrl
    }


}

