//
// TflApiPresentationEntitiesFaresPassengerType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesFaresPassengerType: Codable {

    public var type: String?
    public var _description: String?
    public var displayName: String?
    public var displayOrder: Int?

    public init(type: String?, _description: String?, displayName: String?, displayOrder: Int?) {
        self.type = type
        self._description = _description
        self.displayName = displayName
        self.displayOrder = displayOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _description = "description"
        case displayName
        case displayOrder
    }


}

