//
// TflApiPresentationEntitiesPeriod.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesPeriod: Codable {

    public enum ModelType: String, Codable { 
        case normal = "Normal"
        case frequencyHours = "FrequencyHours"
        case frequencyMinutes = "FrequencyMinutes"
        case unknown = "Unknown"
    }
    public var type: ModelType?
    public var fromTime: TflApiPresentationEntitiesTwentyFourHourClockTime?
    public var toTime: TflApiPresentationEntitiesTwentyFourHourClockTime?
    public var frequency: TflApiPresentationEntitiesServiceFrequency?

    public init(type: ModelType?, fromTime: TflApiPresentationEntitiesTwentyFourHourClockTime?, toTime: TflApiPresentationEntitiesTwentyFourHourClockTime?, frequency: TflApiPresentationEntitiesServiceFrequency?) {
        self.type = type
        self.fromTime = fromTime
        self.toTime = toTime
        self.frequency = frequency
    }


}

