//
// TflApiPresentationEntitiesRoadCorridor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesRoadCorridor: Codable {

    /** The Id of the Corridor e.g. \&quot;A406\&quot; */
    public var _id: String?
    /** The display name of the Corridor e.g. \&quot;North Circular (A406)\&quot;. This              may be identical to the Id. */
    public var displayName: String?
    /** The group name of the Corridor e.g. \&quot;Central London\&quot;. Most corridors are not grouped, in which case this field can be null. */
    public var group: String?
    /** Standard multi-mode status severity code */
    public var statusSeverity: String?
    /** Description of the status severity as applied to RoadCorridors */
    public var statusSeverityDescription: String?
    /** The Bounds of the Corridor, given by the south-east followed by the north-west co-ordinate              pair in geoJSON format e.g. \&quot;[[-1.241531,51.242151],[1.641223,53.765721]]\&quot; */
    public var bounds: String?
    /** The Envelope of the Corridor, given by the corner co-ordinates of a rectangular (four-point) polygon              in geoJSON format e.g. \&quot;[[-1.241531,51.242151],[-1.241531,53.765721],[1.641223,53.765721],[1.641223,51.242151]]\&quot; */
    public var envelope: String?
    /** The start of the period over which status has been aggregated, or null if this is the current corridor status. */
    public var statusAggregationStartDate: Date?
    /** The end of the period over which status has been aggregated, or null if this is the current corridor status. */
    public var statusAggregationEndDate: Date?
    /** URL to retrieve this Corridor. */
    public var url: String?

    public init(_id: String?, displayName: String?, group: String?, statusSeverity: String?, statusSeverityDescription: String?, bounds: String?, envelope: String?, statusAggregationStartDate: Date?, statusAggregationEndDate: Date?, url: String?) {
        self._id = _id
        self.displayName = displayName
        self.group = group
        self.statusSeverity = statusSeverity
        self.statusSeverityDescription = statusSeverityDescription
        self.bounds = bounds
        self.envelope = envelope
        self.statusAggregationStartDate = statusAggregationStartDate
        self.statusAggregationEndDate = statusAggregationEndDate
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case group
        case statusSeverity
        case statusSeverityDescription
        case bounds
        case envelope
        case statusAggregationStartDate
        case statusAggregationEndDate
        case url
    }


}

