//
// TflApiPresentationEntitiesSearchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesSearchResponse: Codable {

    public var query: String?
    public var from: Int?
    public var page: Int?
    public var pageSize: Int?
    public var provider: String?
    public var total: Int?
    public var matches: [TflApiPresentationEntitiesSearchMatch]?
    public var maxScore: Double?

    public init(query: String?, from: Int?, page: Int?, pageSize: Int?, provider: String?, total: Int?, matches: [TflApiPresentationEntitiesSearchMatch]?, maxScore: Double?) {
        self.query = query
        self.from = from
        self.page = page
        self.pageSize = pageSize
        self.provider = provider
        self.total = total
        self.matches = matches
        self.maxScore = maxScore
    }


}

