//
// TflApiPresentationEntitiesJourneyPlannerItineraryResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A DTO representing a list of possible journeys. */

public struct TflApiPresentationEntitiesJourneyPlannerItineraryResult: Codable {

    public var journeys: [TflApiPresentationEntitiesJourneyPlannerJourney]?
    public var lines: [TflApiPresentationEntitiesLine]?
    public var cycleHireDockingStationData: TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData?
    public var stopMessages: [String]?
    public var recommendedMaxAgeMinutes: Int?
    public var searchCriteria: TflApiPresentationEntitiesJourneyPlannerSearchCriteria?
    public var journeyVector: TflApiPresentationEntitiesJourneyPlannerJourneyVector?

    public init(journeys: [TflApiPresentationEntitiesJourneyPlannerJourney]?, lines: [TflApiPresentationEntitiesLine]?, cycleHireDockingStationData: TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData?, stopMessages: [String]?, recommendedMaxAgeMinutes: Int?, searchCriteria: TflApiPresentationEntitiesJourneyPlannerSearchCriteria?, journeyVector: TflApiPresentationEntitiesJourneyPlannerJourneyVector?) {
        self.journeys = journeys
        self.lines = lines
        self.cycleHireDockingStationData = cycleHireDockingStationData
        self.stopMessages = stopMessages
        self.recommendedMaxAgeMinutes = recommendedMaxAgeMinutes
        self.searchCriteria = searchCriteria
        self.journeyVector = journeyVector
    }


}

