//
// TflApiPresentationEntitiesNetworkStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represent travel network status */

public struct TflApiPresentationEntitiesNetworkStatus: Codable {

    public var _operator: String?
    public var status: String?
    public var message: String?
    public var statusLevel: Int?

    public init(_operator: String?, status: String?, message: String?, statusLevel: Int?) {
        self._operator = _operator
        self.status = status
        self.message = message
        self.statusLevel = statusLevel
    }

    public enum CodingKeys: String, CodingKey { 
        case _operator = "operator"
        case status
        case message
        case statusLevel
    }


}

