//
// TflApiPresentationEntitiesDisruption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a disruption to a route within the transport network. */

public struct TflApiPresentationEntitiesDisruption: Codable {

    public enum Category: String, Codable { 
        case undefined = "Undefined"
        case realTime = "RealTime"
        case plannedWork = "PlannedWork"
        case information = "Information"
        case event = "Event"
        case crowding = "Crowding"
        case statusAlert = "StatusAlert"
    }
    /** Gets or sets the category of this dispruption. */
    public var category: Category?
    /** Gets or sets the disruption type of this dispruption. */
    public var type: String?
    /** Gets or sets the description of the category. */
    public var categoryDescription: String?
    /** Gets or sets the description of this disruption. */
    public var _description: String?
    /** Gets or sets the summary of this disruption. */
    public var summary: String?
    /** Gets or sets the additionaInfo of this disruption. */
    public var additionalInfo: String?
    /** Gets or sets the date/time when this disruption was created. */
    public var created: Date?
    /** Gets or sets the date/time when this disruption was last updated. */
    public var lastUpdate: Date?
    /** Gets or sets the routes affected by this disruption */
    public var affectedRoutes: [TflApiPresentationEntitiesRouteSection]?
    /** Gets or sets the stops affected by this disruption */
    public var affectedStops: [TflApiPresentationEntitiesStopPoint]?
    /** Text describing the closure type */
    public var closureText: String?

    public init(category: Category?, type: String?, categoryDescription: String?, _description: String?, summary: String?, additionalInfo: String?, created: Date?, lastUpdate: Date?, affectedRoutes: [TflApiPresentationEntitiesRouteSection]?, affectedStops: [TflApiPresentationEntitiesStopPoint]?, closureText: String?) {
        self.category = category
        self.type = type
        self.categoryDescription = categoryDescription
        self._description = _description
        self.summary = summary
        self.additionalInfo = additionalInfo
        self.created = created
        self.lastUpdate = lastUpdate
        self.affectedRoutes = affectedRoutes
        self.affectedStops = affectedStops
        self.closureText = closureText
    }

    public enum CodingKeys: String, CodingKey { 
        case category
        case type
        case categoryDescription
        case _description = "description"
        case summary
        case additionalInfo
        case created
        case lastUpdate
        case affectedRoutes
        case affectedStops
        case closureText
    }


}

