//
// TflApiPresentationEntitiesRoadProject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesRoadProject: Codable {

    public enum Phase: String, Codable { 
        case unscoped = "Unscoped"
        case concept = "Concept"
        case consultationEnded = "ConsultationEnded"
        case consultation = "Consultation"
        case construction = "Construction"
        case complete = "Complete"
    }
    public var projectId: String?
    public var schemeName: String?
    public var projectName: String?
    public var projectDescription: String?
    public var projectPageUrl: String?
    public var consultationPageUrl: String?
    public var consultationStartDate: Date?
    public var consultationEndDate: Date?
    public var constructionStartDate: Date?
    public var constructionEndDate: Date?
    public var boroughsBenefited: [String]?
    public var cycleSuperhighwayId: String?
    public var phase: Phase?
    public var contactName: String?
    public var contactEmail: String?
    public var externalPageUrl: String?
    public var projectSummaryPageUrl: String?

    public init(projectId: String?, schemeName: String?, projectName: String?, projectDescription: String?, projectPageUrl: String?, consultationPageUrl: String?, consultationStartDate: Date?, consultationEndDate: Date?, constructionStartDate: Date?, constructionEndDate: Date?, boroughsBenefited: [String]?, cycleSuperhighwayId: String?, phase: Phase?, contactName: String?, contactEmail: String?, externalPageUrl: String?, projectSummaryPageUrl: String?) {
        self.projectId = projectId
        self.schemeName = schemeName
        self.projectName = projectName
        self.projectDescription = projectDescription
        self.projectPageUrl = projectPageUrl
        self.consultationPageUrl = consultationPageUrl
        self.consultationStartDate = consultationStartDate
        self.consultationEndDate = consultationEndDate
        self.constructionStartDate = constructionStartDate
        self.constructionEndDate = constructionEndDate
        self.boroughsBenefited = boroughsBenefited
        self.cycleSuperhighwayId = cycleSuperhighwayId
        self.phase = phase
        self.contactName = contactName
        self.contactEmail = contactEmail
        self.externalPageUrl = externalPageUrl
        self.projectSummaryPageUrl = projectSummaryPageUrl
    }


}

