//
// TflApiPresentationEntitiesTimetableRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesTimetableRoute: Codable {

    public var stationIntervals: [TflApiPresentationEntitiesStationInterval]?
    public var schedules: [TflApiPresentationEntitiesSchedule]?

    public init(stationIntervals: [TflApiPresentationEntitiesStationInterval]?, schedules: [TflApiPresentationEntitiesSchedule]?) {
        self.stationIntervals = stationIntervals
        self.schedules = schedules
    }


}

