//
// TflApiPresentationEntitiesDisruptedPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesDisruptedPoint: Codable {

    public var atcoCode: String?
    public var fromDate: Date?
    public var toDate: Date?
    public var _description: String?
    public var commonName: String?
    public var type: String?
    public var mode: String?
    public var stationAtcoCode: String?
    public var appearance: String?
    public var additionalInformation: String?

    public init(atcoCode: String?, fromDate: Date?, toDate: Date?, _description: String?, commonName: String?, type: String?, mode: String?, stationAtcoCode: String?, appearance: String?, additionalInformation: String?) {
        self.atcoCode = atcoCode
        self.fromDate = fromDate
        self.toDate = toDate
        self._description = _description
        self.commonName = commonName
        self.type = type
        self.mode = mode
        self.stationAtcoCode = stationAtcoCode
        self.appearance = appearance
        self.additionalInformation = additionalInformation
    }

    public enum CodingKeys: String, CodingKey { 
        case atcoCode
        case fromDate
        case toDate
        case _description = "description"
        case commonName
        case type
        case mode
        case stationAtcoCode
        case appearance
        case additionalInformation
    }


}

