//
// TflApiPresentationEntitiesTimetable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesTimetable: Codable {

    public var departureStopId: String?
    public var routes: [TflApiPresentationEntitiesTimetableRoute]?

    public init(departureStopId: String?, routes: [TflApiPresentationEntitiesTimetableRoute]?) {
        self.departureStopId = departureStopId
        self.routes = routes
    }


}

