//
// TflApiPresentationEntitiesCoordinate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesCoordinate: Codable {

    public var longitude: Double?
    public var latitude: Double?
    public var easting: Double?
    public var northing: Double?
    public var xCoord: Int?
    public var yCoord: Int?

    public init(longitude: Double?, latitude: Double?, easting: Double?, northing: Double?, xCoord: Int?, yCoord: Int?) {
        self.longitude = longitude
        self.latitude = latitude
        self.easting = easting
        self.northing = northing
        self.xCoord = xCoord
        self.yCoord = yCoord
    }


}

