//
// TflApiPresentationEntitiesRouteSequence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesRouteSequence: Codable {

    public var lineId: String?
    public var lineName: String?
    public var direction: String?
    public var isOutboundOnly: Bool?
    public var mode: String?
    public var lineStrings: [String]?
    public var stations: [TflApiPresentationEntitiesMatchedStop]?
    public var stopPointSequences: [TflApiPresentationEntitiesStopPointSequence]?
    public var orderedLineRoutes: [TflApiPresentationEntitiesOrderedRoute]?

    public init(lineId: String?, lineName: String?, direction: String?, isOutboundOnly: Bool?, mode: String?, lineStrings: [String]?, stations: [TflApiPresentationEntitiesMatchedStop]?, stopPointSequences: [TflApiPresentationEntitiesStopPointSequence]?, orderedLineRoutes: [TflApiPresentationEntitiesOrderedRoute]?) {
        self.lineId = lineId
        self.lineName = lineName
        self.direction = direction
        self.isOutboundOnly = isOutboundOnly
        self.mode = mode
        self.lineStrings = lineStrings
        self.stations = stations
        self.stopPointSequences = stopPointSequences
        self.orderedLineRoutes = orderedLineRoutes
    }


}

