//
// TflApiPresentationEntitiesJourneyPlannerJourneyFare.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesJourneyPlannerJourneyFare: Codable {

    public var totalCost: Int?
    public var fares: [TflApiPresentationEntitiesJourneyPlannerFare]?
    public var caveats: [TflApiPresentationEntitiesJourneyPlannerFareCaveat]?

    public init(totalCost: Int?, fares: [TflApiPresentationEntitiesJourneyPlannerFare]?, caveats: [TflApiPresentationEntitiesJourneyPlannerFareCaveat]?) {
        self.totalCost = totalCost
        self.fares = fares
        self.caveats = caveats
    }


}

