//
// TflApiPresentationEntitiesInstruction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesInstruction: Codable {

    public var summary: String?
    public var detailed: String?
    public var steps: [TflApiPresentationEntitiesInstructionStep]?

    public init(summary: String?, detailed: String?, steps: [TflApiPresentationEntitiesInstructionStep]?) {
        self.summary = summary
        self.detailed = detailed
        self.steps = steps
    }


}

