//
// AccidentStatsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AccidentStatsAPI {
    /**
     Gets all accident details for accidents occuring in the specified year
     
     - parameter year: (path) The year for which to filter the accidents on. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accidentStatsGet(year: Int, completion: @escaping ((_ data: [TflApiPresentationEntitiesAccidentStatsAccidentDetail]?,_ error: Error?) -> Void)) {
        accidentStatsGetWithRequestBuilder(year: year).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Gets all accident details for accidents occuring in the specified year
     - GET /AccidentStats/{year}
     - examples: [{contentType=application/json, example=[ {
  "date" : "2000-01-23T04:56:07.000+00:00",
  "severity" : "severity",
  "vehicles" : [ {
    "type" : "type"
  }, {
    "type" : "type"
  } ],
  "lon" : 1.4658129805029452,
  "location" : "location",
  "id" : 0,
  "borough" : "borough",
  "casualties" : [ {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  }, {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  } ],
  "lat" : 6.027456183070403
}, {
  "date" : "2000-01-23T04:56:07.000+00:00",
  "severity" : "severity",
  "vehicles" : [ {
    "type" : "type"
  }, {
    "type" : "type"
  } ],
  "lon" : 1.4658129805029452,
  "location" : "location",
  "id" : 0,
  "borough" : "borough",
  "casualties" : [ {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  }, {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  } ],
  "lat" : 6.027456183070403
} ]}, {contentType=application/xml, example=<null>
  <id>123</id>
  <lat>3.149</lat>
  <lon>3.149</lon>
  <location>aeiou</location>
  <date>2000-01-23T04:56:07.000Z</date>
  <severity>aeiou</severity>
  <borough>aeiou</borough>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "date" : "2000-01-23T04:56:07.000+00:00",
  "severity" : "severity",
  "vehicles" : [ {
    "type" : "type"
  }, {
    "type" : "type"
  } ],
  "lon" : 1.4658129805029452,
  "location" : "location",
  "id" : 0,
  "borough" : "borough",
  "casualties" : [ {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  }, {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  } ],
  "lat" : 6.027456183070403
}, {
  "date" : "2000-01-23T04:56:07.000+00:00",
  "severity" : "severity",
  "vehicles" : [ {
    "type" : "type"
  }, {
    "type" : "type"
  } ],
  "lon" : 1.4658129805029452,
  "location" : "location",
  "id" : 0,
  "borough" : "borough",
  "casualties" : [ {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  }, {
    "severity" : "severity",
    "mode" : "mode",
    "ageBand" : "ageBand",
    "class" : "class",
    "age" : 5
  } ],
  "lat" : 6.027456183070403
} ]}, {contentType=application/xml, example=<null>
  <id>123</id>
  <lat>3.149</lat>
  <lon>3.149</lon>
  <location>aeiou</location>
  <date>2000-01-23T04:56:07.000Z</date>
  <severity>aeiou</severity>
  <borough>aeiou</borough>
</null>}]
     
     - parameter year: (path) The year for which to filter the accidents on. 

     - returns: RequestBuilder<[TflApiPresentationEntitiesAccidentStatsAccidentDetail]> 
     */
    open class func accidentStatsGetWithRequestBuilder(year: Int) -> RequestBuilder<[TflApiPresentationEntitiesAccidentStatsAccidentDetail]> {
        var path = "/AccidentStats/{year}"
        let yearPreEscape = "\(year)"
        let yearPostEscape = yearPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{year}", with: yearPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[TflApiPresentationEntitiesAccidentStatsAccidentDetail]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
