//
// SystemDataSpatialDbGeography.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SystemDataSpatialDbGeography: Codable {

    public var geography: SystemDataSpatialDbGeographyWellKnownValue?

    public init(geography: SystemDataSpatialDbGeographyWellKnownValue?) {
        self.geography = geography
    }


}

