//
// TflApiPresentationEntitiesPredictionTiming.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesPredictionTiming: Codable {

    public var countdownServerAdjustment: String?
    public var source: Date?
    public var insert: Date?
    public var read: Date?
    public var sent: Date?
    public var received: Date?

    public init(countdownServerAdjustment: String?, source: Date?, insert: Date?, read: Date?, sent: Date?, received: Date?) {
        self.countdownServerAdjustment = countdownServerAdjustment
        self.source = source
        self.insert = insert
        self.read = read
        self.sent = sent
        self.received = received
    }


}

