//
// TflApiPresentationEntitiesTimetablesDisambiguation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesTimetablesDisambiguation: Codable {

    public var disambiguationOptions: [TflApiPresentationEntitiesTimetablesDisambiguationOption]?

    public init(disambiguationOptions: [TflApiPresentationEntitiesTimetablesDisambiguationOption]?) {
        self.disambiguationOptions = disambiguationOptions
    }


}

