//
// TflApiPresentationEntitiesKnownJourney.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesKnownJourney: Codable {

    public var hour: String?
    public var minute: String?
    public var intervalId: Int?

    public init(hour: String?, minute: String?, intervalId: Int?) {
        self.hour = hour
        self.minute = minute
        self.intervalId = intervalId
    }


}

