//
// TflApiPresentationEntitiesLineRouteSection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesLineRouteSection: Codable {

    public var routeId: Int?
    public var direction: String?
    public var destination: String?
    public var fromStation: String?
    public var toStation: String?
    public var serviceType: String?
    public var vehicleDestinationText: String?

    public init(routeId: Int?, direction: String?, destination: String?, fromStation: String?, toStation: String?, serviceType: String?, vehicleDestinationText: String?) {
        self.routeId = routeId
        self.direction = direction
        self.destination = destination
        self.fromStation = fromStation
        self.toStation = toStation
        self.serviceType = serviceType
        self.vehicleDestinationText = vehicleDestinationText
    }


}

