//
// TflApiPresentationEntitiesTimetableResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesTimetableResponse: Codable {

    public var lineId: String?
    public var lineName: String?
    public var direction: String?
    public var pdfUrl: String?
    public var stations: [TflApiPresentationEntitiesMatchedStop]?
    public var stops: [TflApiPresentationEntitiesMatchedStop]?
    public var timetable: TflApiPresentationEntitiesTimetable?
    public var disambiguation: TflApiPresentationEntitiesTimetablesDisambiguation?
    public var statusErrorMessage: String?

    public init(lineId: String?, lineName: String?, direction: String?, pdfUrl: String?, stations: [TflApiPresentationEntitiesMatchedStop]?, stops: [TflApiPresentationEntitiesMatchedStop]?, timetable: TflApiPresentationEntitiesTimetable?, disambiguation: TflApiPresentationEntitiesTimetablesDisambiguation?, statusErrorMessage: String?) {
        self.lineId = lineId
        self.lineName = lineName
        self.direction = direction
        self.pdfUrl = pdfUrl
        self.stations = stations
        self.stops = stops
        self.timetable = timetable
        self.disambiguation = disambiguation
        self.statusErrorMessage = statusErrorMessage
    }


}

