//
// TflApiPresentationEntitiesLineStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesLineStatus: Codable {

    public var _id: Int?
    public var lineId: String?
    public var statusSeverity: Int?
    public var statusSeverityDescription: String?
    public var reason: String?
    public var created: Date?
    public var modified: Date?
    public var validityPeriods: [TflApiPresentationEntitiesValidityPeriod]?
    public var disruption: TflApiPresentationEntitiesDisruption?

    public init(_id: Int?, lineId: String?, statusSeverity: Int?, statusSeverityDescription: String?, reason: String?, created: Date?, modified: Date?, validityPeriods: [TflApiPresentationEntitiesValidityPeriod]?, disruption: TflApiPresentationEntitiesDisruption?) {
        self._id = _id
        self.lineId = lineId
        self.statusSeverity = statusSeverity
        self.statusSeverityDescription = statusSeverityDescription
        self.reason = reason
        self.created = created
        self.modified = modified
        self.validityPeriods = validityPeriods
        self.disruption = disruption
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case lineId
        case statusSeverity
        case statusSeverityDescription
        case reason
        case created
        case modified
        case validityPeriods
        case disruption
    }


}

