//
// TflApiPresentationEntitiesLineServiceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesLineServiceType: Codable {

    public var lineName: String?
    public var lineSpecificServiceTypes: [TflApiPresentationEntitiesLineSpecificServiceType]?

    public init(lineName: String?, lineSpecificServiceTypes: [TflApiPresentationEntitiesLineSpecificServiceType]?) {
        self.lineName = lineName
        self.lineSpecificServiceTypes = lineSpecificServiceTypes
    }


}

