//
// TflApiPresentationEntitiesTwentyFourHourClockTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesTwentyFourHourClockTime: Codable {

    public var hour: String?
    public var minute: String?

    public init(hour: String?, minute: String?) {
        self.hour = hour
        self.minute = minute
    }


}

