//
// TflApiPresentationEntitiesInstructionStep.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesInstructionStep: Codable {

    public enum SkyDirectionDescription: String, Codable { 
        case north = "North"
        case northEast = "NorthEast"
        case east = "East"
        case southEast = "SouthEast"
        case south = "South"
        case southWest = "SouthWest"
        case west = "West"
        case northWest = "NorthWest"
    }
    public enum TrackType: String, Codable { 
        case cycleSuperHighway = "CycleSuperHighway"
        case canalTowpath = "CanalTowpath"
        case quietRoad = "QuietRoad"
        case provisionForCyclists = "ProvisionForCyclists"
        case busyRoads = "BusyRoads"
        case _none = "None"
        case pushBike = "PushBike"
        case quietway = "Quietway"
    }
    public var _description: String?
    public var turnDirection: String?
    public var streetName: String?
    public var distance: Int?
    public var cumulativeDistance: Int?
    public var skyDirection: Int?
    public var skyDirectionDescription: SkyDirectionDescription?
    public var cumulativeTravelTime: Int?
    public var latitude: Double?
    public var longitude: Double?
    public var pathAttribute: TflApiPresentationEntitiesPathAttribute?
    public var descriptionHeading: String?
    public var trackType: TrackType?

    public init(_description: String?, turnDirection: String?, streetName: String?, distance: Int?, cumulativeDistance: Int?, skyDirection: Int?, skyDirectionDescription: SkyDirectionDescription?, cumulativeTravelTime: Int?, latitude: Double?, longitude: Double?, pathAttribute: TflApiPresentationEntitiesPathAttribute?, descriptionHeading: String?, trackType: TrackType?) {
        self._description = _description
        self.turnDirection = turnDirection
        self.streetName = streetName
        self.distance = distance
        self.cumulativeDistance = cumulativeDistance
        self.skyDirection = skyDirection
        self.skyDirectionDescription = skyDirectionDescription
        self.cumulativeTravelTime = cumulativeTravelTime
        self.latitude = latitude
        self.longitude = longitude
        self.pathAttribute = pathAttribute
        self.descriptionHeading = descriptionHeading
        self.trackType = trackType
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case turnDirection
        case streetName
        case distance
        case cumulativeDistance
        case skyDirection
        case skyDirectionDescription
        case cumulativeTravelTime
        case latitude
        case longitude
        case pathAttribute
        case descriptionHeading
        case trackType
    }


}

