//
// TflApiPresentationEntitiesSchedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesSchedule: Codable {

    public var name: String?
    public var knownJourneys: [TflApiPresentationEntitiesKnownJourney]?
    public var firstJourney: TflApiPresentationEntitiesKnownJourney?
    public var lastJourney: TflApiPresentationEntitiesKnownJourney?
    public var periods: [TflApiPresentationEntitiesPeriod]?

    public init(name: String?, knownJourneys: [TflApiPresentationEntitiesKnownJourney]?, firstJourney: TflApiPresentationEntitiesKnownJourney?, lastJourney: TflApiPresentationEntitiesKnownJourney?, periods: [TflApiPresentationEntitiesPeriod]?) {
        self.name = name
        self.knownJourneys = knownJourneys
        self.firstJourney = firstJourney
        self.lastJourney = lastJourney
        self.periods = periods
    }


}

