//
// TflApiPresentationEntitiesFaresFareBounds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesFaresFareBounds: Codable {

    public var _id: Int?
    public var from: String?
    public var to: String?
    public var via: String?
    public var routeCode: String?
    public var _description: String?
    public var displayName: String?
    public var _operator: String?
    public var displayOrder: Int?
    public var isPopularFare: Bool?
    public var isPopularTravelCard: Bool?
    public var isTour: Bool?
    public var messages: [TflApiPresentationEntitiesMessage]?

    public init(_id: Int?, from: String?, to: String?, via: String?, routeCode: String?, _description: String?, displayName: String?, _operator: String?, displayOrder: Int?, isPopularFare: Bool?, isPopularTravelCard: Bool?, isTour: Bool?, messages: [TflApiPresentationEntitiesMessage]?) {
        self._id = _id
        self.from = from
        self.to = to
        self.via = via
        self.routeCode = routeCode
        self._description = _description
        self.displayName = displayName
        self._operator = _operator
        self.displayOrder = displayOrder
        self.isPopularFare = isPopularFare
        self.isPopularTravelCard = isPopularTravelCard
        self.isTour = isTour
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case from
        case to
        case via
        case routeCode
        case _description = "description"
        case displayName
        case _operator = "operator"
        case displayOrder
        case isPopularFare
        case isPopularTravelCard
        case isTour
        case messages
    }


}

