//
// TflApiPresentationEntitiesJourneyPlannerFareTap.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesJourneyPlannerFareTap: Codable {

    public var atcoCode: String?
    public var tapDetails: TflApiPresentationEntitiesJourneyPlannerFareTapDetails?

    public init(atcoCode: String?, tapDetails: TflApiPresentationEntitiesJourneyPlannerFareTapDetails?) {
        self.atcoCode = atcoCode
        self.tapDetails = tapDetails
    }


}

