//
// TflApiPresentationEntitiesActiveServiceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesActiveServiceType: Codable {

    public var mode: String?
    public var serviceType: String?

    public init(mode: String?, serviceType: String?) {
        self.mode = mode
        self.serviceType = serviceType
    }


}

