//
// TflApiPresentationEntitiesOrderedRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesOrderedRoute: Codable {

    public var name: String?
    public var naptanIds: [String]?
    public var serviceType: String?

    public init(name: String?, naptanIds: [String]?, serviceType: String?) {
        self.name = name
        self.naptanIds = naptanIds
        self.serviceType = serviceType
    }


}

