//
// TflApiPresentationEntitiesFaresRecommendationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesFaresRecommendationResponse: Codable {

    public var recommendations: [TflApiPresentationEntitiesFaresRecommendation]?

    public init(recommendations: [TflApiPresentationEntitiesFaresRecommendation]?) {
        self.recommendations = recommendations
    }


}

