//
// TflApiPresentationEntitiesPlace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesPlace: Codable {

    /** A unique identifier. */
    public var _id: String?
    /** The unique location of this resource. */
    public var url: String?
    /** A human readable name. */
    public var commonName: String?
    /** The distance of the place from its search point, if this is the result              of a geographical search, otherwise zero. */
    public var distance: Double?
    /** The type of Place. See /Place/Meta/placeTypes for possible values. */
    public var placeType: String?
    /** A bag of additional key/value pairs with extra information about this place. */
    public var additionalProperties: [TflApiPresentationEntitiesAdditionalProperties]?
    public var children: [TflApiPresentationEntitiesPlace]?
    public var childrenUrls: [String]?
    /** WGS84 latitude of the location. */
    public var lat: Double?
    /** WGS84 longitude of the location. */
    public var lon: Double?

    public init(_id: String?, url: String?, commonName: String?, distance: Double?, placeType: String?, additionalProperties: [TflApiPresentationEntitiesAdditionalProperties]?, children: [TflApiPresentationEntitiesPlace]?, childrenUrls: [String]?, lat: Double?, lon: Double?) {
        self._id = _id
        self.url = url
        self.commonName = commonName
        self.distance = distance
        self.placeType = placeType
        self.additionalProperties = additionalProperties
        self.children = children
        self.childrenUrls = childrenUrls
        self.lat = lat
        self.lon = lon
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case url
        case commonName
        case distance
        case placeType
        case additionalProperties
        case children
        case childrenUrls
        case lat
        case lon
    }


}

