//
// TflApiPresentationEntitiesIdentifier.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesIdentifier: Codable {

    public enum RouteType: String, Codable { 
        case unknown = "Unknown"
        case all = "All"
        case cycleSuperhighways = "Cycle Superhighways"
        case quietways = "Quietways"
        case cycleways = "Cycleways"
        case miniHollands = "Mini-Hollands"
        case centralLondonGrid = "Central London Grid"
    }
    public enum Status: String, Codable { 
        case unknown = "Unknown"
        case all = "All"
        case _open = "Open"
        case inProgress = "In Progress"
        case planned = "Planned"
        case plannedSubjectToFeasibilityAndConsultation = "Planned - Subject to feasibility and consultation."
        case notOpen = "Not Open"
    }
    public var _id: String?
    public var name: String?
    public var uri: String?
    public var fullName: String?
    public var type: String?
    public var crowding: TflApiPresentationEntitiesCrowding?
    public var routeType: RouteType?
    public var status: Status?

    public init(_id: String?, name: String?, uri: String?, fullName: String?, type: String?, crowding: TflApiPresentationEntitiesCrowding?, routeType: RouteType?, status: Status?) {
        self._id = _id
        self.name = name
        self.uri = uri
        self.fullName = fullName
        self.type = type
        self.crowding = crowding
        self.routeType = routeType
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case uri
        case fullName
        case type
        case crowding
        case routeType
        case status
    }


}

