//
// TflApiPresentationEntitiesJourneyPlannerTimeAdjustments.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesJourneyPlannerTimeAdjustments: Codable {

    public var earliest: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?
    public var earlier: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?
    public var later: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?
    public var latest: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?

    public init(earliest: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?, earlier: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?, later: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?, latest: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment?) {
        self.earliest = earliest
        self.earlier = earlier
        self.later = later
        self.latest = latest
    }


}

