//
// TflApiPresentationEntitiesLineModeGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TflApiPresentationEntitiesLineModeGroup: Codable {

    public var modeName: String?
    public var lineIdentifier: [String]?

    public init(modeName: String?, lineIdentifier: [String]?) {
        self.modeName = modeName
        self.lineIdentifier = lineIdentifier
    }


}

