//
// AccidentStatsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class AccidentStatsAPI: APIBase {
    /**
     Gets all accident details for accidents occuring in the specified year
     
     - parameter year: (path) The year for which to filter the accidents on. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accidentStatsGet(year: Int32, completion: @escaping ((_ data: [AccidentDetail]?,_ error: Error?) -> Void)) {
        accidentStatsGetWithRequestBuilder(year: year).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Gets all accident details for accidents occuring in the specified year
     - GET /AccidentStats/{year}
     - examples: [{contentType=application/json, example=[ {
  "date" : "2000-01-23T04:56:07.000+00:00",
  "severity" : "aeiou",
  "vehicles" : [ {
    "type" : "aeiou"
  } ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "location" : "aeiou",
  "id" : 123,
  "borough" : "aeiou",
  "casualties" : [ {
    "severity" : "aeiou",
    "mode" : "aeiou",
    "ageBand" : "aeiou",
    "class" : "aeiou",
    "age" : 123
  } ],
  "lat" : 1.3579000000000001069366817318950779736042022705078125
} ]}, {contentType=application/xml, example=<null>
  <id>0</id>
  <lat>not implemented io.swagger.models.properties.DoubleProperty@6e01b9a8</lat>
  <lon>not implemented io.swagger.models.properties.DoubleProperty@6e01b9a8</lon>
  <location>string</location>
  <date>2000-01-23T04:56:07.000Z</date>
  <severity>string</severity>
  <borough>string</borough>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "date" : "2000-01-23T04:56:07.000+00:00",
  "severity" : "aeiou",
  "vehicles" : [ {
    "type" : "aeiou"
  } ],
  "lon" : 1.3579000000000001069366817318950779736042022705078125,
  "location" : "aeiou",
  "id" : 123,
  "borough" : "aeiou",
  "casualties" : [ {
    "severity" : "aeiou",
    "mode" : "aeiou",
    "ageBand" : "aeiou",
    "class" : "aeiou",
    "age" : 123
  } ],
  "lat" : 1.3579000000000001069366817318950779736042022705078125
} ]}, {contentType=application/xml, example=<null>
  <id>0</id>
  <lat>not implemented io.swagger.models.properties.DoubleProperty@6e01b9a8</lat>
  <lon>not implemented io.swagger.models.properties.DoubleProperty@6e01b9a8</lon>
  <location>string</location>
  <date>2000-01-23T04:56:07.000Z</date>
  <severity>string</severity>
  <borough>string</borough>
</null>}]
     
     - parameter year: (path) The year for which to filter the accidents on. 

     - returns: RequestBuilder<[AccidentDetail]> 
     */
    open class func accidentStatsGetWithRequestBuilder(year: Int32) -> RequestBuilder<[AccidentDetail]> {
        var path = "/AccidentStats/{year}"
        path = path.replacingOccurrences(of: "{year}", with: "\(year)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[AccidentDetail]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
