//
// AirQualityAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class AirQualityAPI: APIBase {
    /**
     Gets air quality data feed
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func airQualityGet(completion: @escaping ((_ data: Object?,_ error: Error?) -> Void)) {
        airQualityGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Gets air quality data feed
     - GET /AirQuality
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]

     - returns: RequestBuilder<Object> 
     */
    open class func airQualityGetWithRequestBuilder() -> RequestBuilder<Object> {
        let path = "/AirQuality"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Object>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
