//
// OccupancyAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class OccupancyAPI: APIBase {
    /**
     Gets the occupancy for a car park with a given id
     
     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func occupancyGet(id: String, completion: @escaping ((_ data: CarParkOccupancy?,_ error: Error?) -> Void)) {
        occupancyGetWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Gets the occupancy for a car park with a given id
     - GET /Occupancy/CarPark/{id}
     - examples: [{contentType=application/json, example={
  "carParkDetailsUrl" : "aeiou",
  "bays" : [ {
    "bayCount" : 123,
    "free" : 123,
    "bayType" : "aeiou",
    "occupied" : 123
  } ],
  "name" : "aeiou",
  "id" : "aeiou"
}}, {contentType=application/xml, example=<null>
  <id>string</id>
  <name>string</name>
  <carParkDetailsUrl>string</carParkDetailsUrl>
</null>}]
     - examples: [{contentType=application/json, example={
  "carParkDetailsUrl" : "aeiou",
  "bays" : [ {
    "bayCount" : 123,
    "free" : 123,
    "bayType" : "aeiou",
    "occupied" : 123
  } ],
  "name" : "aeiou",
  "id" : "aeiou"
}}, {contentType=application/xml, example=<null>
  <id>string</id>
  <name>string</name>
  <carParkDetailsUrl>string</carParkDetailsUrl>
</null>}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<CarParkOccupancy> 
     */
    open class func occupancyGetWithRequestBuilder(id: String) -> RequestBuilder<CarParkOccupancy> {
        var path = "/Occupancy/CarPark/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<CarParkOccupancy>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Gets the occupancy for all car parks that have occupancy data
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func occupancyGet_0(completion: @escaping ((_ data: [CarParkOccupancy]?,_ error: Error?) -> Void)) {
        occupancyGet_0WithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Gets the occupancy for all car parks that have occupancy data
     - GET /Occupancy/CarPark
     - examples: [{contentType=application/json, example=[ {
  "carParkDetailsUrl" : "aeiou",
  "bays" : [ {
    "bayCount" : 123,
    "free" : 123,
    "bayType" : "aeiou",
    "occupied" : 123
  } ],
  "name" : "aeiou",
  "id" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>string</id>
  <name>string</name>
  <carParkDetailsUrl>string</carParkDetailsUrl>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "carParkDetailsUrl" : "aeiou",
  "bays" : [ {
    "bayCount" : 123,
    "free" : 123,
    "bayType" : "aeiou",
    "occupied" : 123
  } ],
  "name" : "aeiou",
  "id" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <id>string</id>
  <name>string</name>
  <carParkDetailsUrl>string</carParkDetailsUrl>
</null>}]

     - returns: RequestBuilder<[CarParkOccupancy]> 
     */
    open class func occupancyGet_0WithRequestBuilder() -> RequestBuilder<[CarParkOccupancy]> {
        let path = "/Occupancy/CarPark"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[CarParkOccupancy]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
