//
// CacheSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CacheSettings: JSONEncodable {
    public var cacheName: String?
    public var maxItemTtlSecondsOverride: Int32?
    public var settingsTtlSecondsOverride: Int32?
    public var lastInvalidated: Date?
    public var modifiedDate: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["cacheName"] = self.cacheName
        nillableDictionary["maxItemTtlSecondsOverride"] = self.maxItemTtlSecondsOverride?.encodeToJSON()
        nillableDictionary["settingsTtlSecondsOverride"] = self.settingsTtlSecondsOverride?.encodeToJSON()
        nillableDictionary["lastInvalidated"] = self.lastInvalidated?.encodeToJSON()
        nillableDictionary["modifiedDate"] = self.modifiedDate?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
