//
// AirQualityAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AirQualityAPI {
    /**
     Gets air quality data feed
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func airQualityGet(completion: @escaping ((_ data: SystemObject?,_ error: Error?) -> Void)) {
        airQualityGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Gets air quality data feed
     - GET /AirQuality
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]
     - examples: [{contentType=application/json, example={ }}, {contentType=application/xml, example=<null>
</null>}]

     - returns: RequestBuilder<SystemObject> 
     */
    open class func airQualityGetWithRequestBuilder() -> RequestBuilder<SystemObject> {
        let path = "/AirQuality"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<SystemObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
